// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const app: string;
export const appLogo: string;
export const appHeader: string;
export const appTitle: string;
export const appIntro: string;
export const columnHeaderUpdate: string;
export const appLogoSpin: string;
